- name: Kubeadm | Master | Check etcd cluster health
  shell: |
    etcdctl --endpoints=https://127.0.0.1:2379 endpoint --cluster health
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CACERT: /etc/kubernetes/pki/etcd/ca.crt
    ETCDCTL_CERT: /etc/kubernetes/pki/etcd/peer.crt
    ETCDCTL_KEY: /etc/kubernetes/pki/etcd/peer.key
  register: etcd_health
  changed_when: false
  ignore_errors: yes
  run_once: yes
  when: item != inventory_hostname
  delegate_to: "{{ item }}" 
  with_items: "{{ groups['master'] }}"

- debug:
    var: etcd_health
    verbosity: 2


- name: Kubeadm | Master | Remove etcd unhealthy members
  shell: |
    export UNHEALTHY_ENDPOINT=$(etcdctl --endpoints=https://127.0.0.1:2379 endpoint --cluster health 2>&1  | grep "unhealthy:" | awk -F " " '{print $1}')
    export UNHEALTHY_ENDPOINT_ID=$(etcdctl --endpoints=https://127.0.0.1:2379 member list | awk -v unhealthy_endpoint="$UNHEALTHY_ENDPOINT" -F ", " '($5 == unhealthy_endpoint){print $1}')    
    etcdctl --endpoints=https://127.0.0.1:2379 member remove ${UNHEALTHY_ENDPOINT_ID}
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CACERT: /etc/kubernetes/pki/etcd/ca.crt
    ETCDCTL_CERT: /etc/kubernetes/pki/etcd/peer.crt
    ETCDCTL_KEY: /etc/kubernetes/pki/etcd/peer.key
  changed_when: false
  run_once: yes
  ignore_errors: yes
  when: ( item != inventory_hostname ) and (( etcd_health['results'] | random(seed=inventory_hostname)).rc is defined ) and (( etcd_health['results'] | random(seed=inventory_hostname)).rc != 0 )
  delegate_to: "{{ item }}" 
  with_items: "{{ groups['master'] }}"

- name: Kubeadm | Master | Check if node is in cluster
  shell: |
    etcdctl --endpoints=https://127.0.0.1:2379 -w json member list | jq -r --unbuffered -e --arg node "{{ inventory_hostname }}" '.members[]?| select(.name == $node ) | .name'
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CACERT: /etc/kubernetes/pki/etcd/ca.crt
    ETCDCTL_CERT: /etc/kubernetes/pki/etcd/peer.crt
    ETCDCTL_KEY: /etc/kubernetes/pki/etcd/peer.key
  register: node_in_cluster
  when: item != inventory_hostname
  run_once: yes
  ignore_errors: yes
  delegate_to: "{{ item }}" 
  with_items: "{{ groups['master'] }}"

- name: Kubeadm | Master | Add etcd node to existing cluster
  shell: |
    etcdctl --endpoints=https://127.0.0.1:2379 member add "{{ inventory_hostname }}" --peer-urls=https://"{{ ansible_env.COREOS_PRIVATE_IPV4 }}":2380
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CACERT: /etc/kubernetes/pki/etcd/ca.crt
    ETCDCTL_CERT: /etc/kubernetes/pki/etcd/peer.crt
    ETCDCTL_KEY: /etc/kubernetes/pki/etcd/peer.key
  register: new_node_added 
  delegate_to: "{{ item }}" 
  with_items: "{{ groups['master'] }}"
  run_once: yes
  ignore_errors: yes
  when: ( item != inventory_hostname )