---
- name: Kubeadm | Master | Copy admin kubeconfig to ansible host
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "kubeconfig/{{ kubeadm_cluster_name }}/admin.conf"
    flat: yes
  run_once: yes
