---
- include_tasks: controlplane_check.yml

- include_tasks: etcd_cleanup.yml
  when: kubernetes_control_plane_local.rc == 2 and kubernetes_control_plane_delegated is success

- include_tasks: kubeadm.yml

- include_tasks: kubeconfig.yml
