---
- include_tasks: sync_certs.yml

- name: Kubeadm | Certs phase
  shell: |
    {{ bin_dir }}/kubeadm alpha phase certs all --config kubeadm-config.yaml
  args:
    chdir: "{{ kubeadm_exec_dir }}"
  run_once: yes

- include_tasks: sync_certs.yml

- name: Kubeadm | Certs phase
  shell: |
    {{ bin_dir }}/kubeadm alpha phase certs all --config kubeadm-config.yaml
  args:
    chdir: "{{ kubeadm_exec_dir }}"