---
- include_tasks: check.yml

- include_tasks: kubeadm.yml
  when:
  - (ansible_fqdn|lower) not in nodes.stdout
  - (ansible_hostname|lower) not in nodes.stdout
  - (inventory_hostname|lower) not in nodes.stdout

